language: node_js
node_js:
  - '10.15.3'
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
  # - yarn test:coverage
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
